#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p generated

bun -e '
const fs = require("fs");
const sourcePath = "grammar/VCL.g4";
const outputPath = "generated/vcl-grammar-source.ts";
const grammar = fs.readFileSync(sourcePath, "utf8");
const out = `// Auto-generated by scripts/update-grammar-source.sh\n// Source: grammar/VCL.g4\n\nconst VCL_GRAMMAR_SOURCE = ${JSON.stringify(grammar)};\n\nexport { VCL_GRAMMAR_SOURCE };\n`;
fs.writeFileSync(outputPath, out);
'
